### ISSUE TITLE
Open Discussion

### ISSUE THREAD

**Issue by GeorgeS2019** [SirWaffle/local-ai-code-completion#1]
Have you considered TorchSharp? The .NET version of PyTorch for working with HuggingFace?
Some of these topics could possibly be discussed not through issues but discussion.

**Comment by SirWaffle** [comment]
yeah, I plan on swapping all my cpu based math over to [TorchSharp ](https://github.com/dotnet/TorchSharp) - however, the huggingface code is all python for pytorch. I've already hooked things up through calling into python, so this time around I'm trying to cut the dependency on python + all the python dependencies. I should be able to write CUDA ( or whatever torch device ) accelerated code and talk with ONNX all on the same device with TorchSharp

**Comment by GeorgeS2019** [comment]
@SirWaffle ML.NET now support HuggingFace [Tokeniers ](https://github.com/dotnet/machinelearning/pull/6272)( replace BlingFire) 

What is the purpose of CodeGen?  The 300+MB ONNX you have submitted to HuggingFace?

**Comment by SirWaffle** [comment]
ah, i'll check out ML.net, on first glance it didnt seem to do what i want, but I havent followed that one as much.

the codeGen ONNX model is just the conversion of the pytorch codegen-350m model to ONNX, with no changes. I put it up there for anyone who doesnt want to install python + python deps to convert the model themselves

**Comment by GeorgeS2019** [comment]
> i'll check out ML.net, 

Thanks for sharing your goal: CodeGen

For Language Generation, ML.NET not there yet.   TorchSharp still have yet to sort out how best to support TorchText.

For Audio, we have a community member who single handedly deliver TorchAudio for TorchSharp
