### ISSUE TITLE
Reusable Post processing modules

### ISSUE THREAD

**Issue by GeorgeS2019** [SirWaffle/local-ai-code-completion#2]
- [ ] Adding **beam search**, and **multiple samples** to the generation code
- [ ] making post processing steps ( searches, softmax, top_k, top_p ) operate in GPU to avoid costly CPU <-> GPU copies of tensors

Some of these functions are provided by ONNX Extensions

**Comment by SirWaffle** [comment]
I only gave the ONNX extensions a quick glance, so I'll go review those, Thanks for insight! I will still most likely write some of these things in TorchSharp, since they aren't all that tricky, and I need to familiarize myself with torchSharp for some other .net based ONNX projects.

**Comment by GeorgeS2019** [comment]
> I need to familiarize myself with torchSharp for some other .net based ONNX projects.

Elaborate please. 

Also do share what you are thinking and need others for feedback related to your TorchSharp [here](https://github.com/dotnet/TorchSharp/discussions)
